package com.models;

import java.math.BigDecimal;
import java.util.Date;

public class ParkingInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_info.id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_info.city_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_info.parking_name
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private String parkingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_info.serial_number
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_info.traffic_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long trafficId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_info.property_type_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long propertyTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_info.adsense_cnt
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long adsenseCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_info.adsense_on_cnt
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long adsenseOnCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_info.status
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_info.profit_share
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long profitShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_info.create_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_info.update_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_info.enabled
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Byte enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_info.detail_address
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private String detailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_info.lng
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private BigDecimal lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_info.lat
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private BigDecimal lat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_info.id
     *
     * @return the value of parking_info.id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_info.id
     *
     * @param id the value for parking_info.id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_info.city_id
     *
     * @return the value of parking_info.city_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_info.city_id
     *
     * @param cityId the value for parking_info.city_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_info.parking_name
     *
     * @return the value of parking_info.parking_name
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public String getParkingName() {
        return parkingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_info.parking_name
     *
     * @param parkingName the value for parking_info.parking_name
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setParkingName(String parkingName) {
        this.parkingName = parkingName == null ? null : parkingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_info.serial_number
     *
     * @return the value of parking_info.serial_number
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_info.serial_number
     *
     * @param serialNumber the value for parking_info.serial_number
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_info.traffic_id
     *
     * @return the value of parking_info.traffic_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getTrafficId() {
        return trafficId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_info.traffic_id
     *
     * @param trafficId the value for parking_info.traffic_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setTrafficId(Long trafficId) {
        this.trafficId = trafficId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_info.property_type_id
     *
     * @return the value of parking_info.property_type_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getPropertyTypeId() {
        return propertyTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_info.property_type_id
     *
     * @param propertyTypeId the value for parking_info.property_type_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setPropertyTypeId(Long propertyTypeId) {
        this.propertyTypeId = propertyTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_info.adsense_cnt
     *
     * @return the value of parking_info.adsense_cnt
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getAdsenseCnt() {
        return adsenseCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_info.adsense_cnt
     *
     * @param adsenseCnt the value for parking_info.adsense_cnt
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setAdsenseCnt(Long adsenseCnt) {
        this.adsenseCnt = adsenseCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_info.adsense_on_cnt
     *
     * @return the value of parking_info.adsense_on_cnt
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getAdsenseOnCnt() {
        return adsenseOnCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_info.adsense_on_cnt
     *
     * @param adsenseOnCnt the value for parking_info.adsense_on_cnt
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setAdsenseOnCnt(Long adsenseOnCnt) {
        this.adsenseOnCnt = adsenseOnCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_info.status
     *
     * @return the value of parking_info.status
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_info.status
     *
     * @param status the value for parking_info.status
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_info.profit_share
     *
     * @return the value of parking_info.profit_share
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getProfitShare() {
        return profitShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_info.profit_share
     *
     * @param profitShare the value for parking_info.profit_share
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setProfitShare(Long profitShare) {
        this.profitShare = profitShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_info.create_time
     *
     * @return the value of parking_info.create_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_info.create_time
     *
     * @param createTime the value for parking_info.create_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_info.update_time
     *
     * @return the value of parking_info.update_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_info.update_time
     *
     * @param updateTime the value for parking_info.update_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_info.enabled
     *
     * @return the value of parking_info.enabled
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Byte getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_info.enabled
     *
     * @param enabled the value for parking_info.enabled
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setEnabled(Byte enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_info.detail_address
     *
     * @return the value of parking_info.detail_address
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_info.detail_address
     *
     * @param detailAddress the value for parking_info.detail_address
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress == null ? null : detailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_info.lng
     *
     * @return the value of parking_info.lng
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public BigDecimal getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_info.lng
     *
     * @param lng the value for parking_info.lng
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setLng(BigDecimal lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_info.lat
     *
     * @return the value of parking_info.lat
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public BigDecimal getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_info.lat
     *
     * @param lat the value for parking_info.lat
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setLat(BigDecimal lat) {
        this.lat = lat;
    }
}