package com.dao;

import com.models.positionInfo;
import com.models.positionInfoExample;
import java.util.List;

public interface PositionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adsense_position_info
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adsense_position_info
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    int insert(positionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adsense_position_info
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    int insertSelective(positionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adsense_position_info
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    List<positionInfo> selectByExample(positionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adsense_position_info
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    positionInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adsense_position_info
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    int updateByPrimaryKeySelective(positionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adsense_position_info
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    int updateByPrimaryKey(positionInfo record);
}