package com.models;

import java.util.Date;

public class AdAlliance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_alliance.id
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_alliance.ad_id
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    private String adId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_alliance.park_id
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    private String parkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_alliance.partner_id
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    private String partnerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_alliance.adsense_position_id
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    private Long adsensePositionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_alliance.uuid
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_alliance.img_url
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_alliance.redirect_url
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    private String redirectUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_alliance.iurl
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    private String iurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_alliance.curl
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    private String curl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_alliance.click_status
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    private Byte clickStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_alliance.create_time
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_alliance.update_time
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_alliance.id
     *
     * @return the value of ad_alliance.id
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_alliance.id
     *
     * @param id the value for ad_alliance.id
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_alliance.ad_id
     *
     * @return the value of ad_alliance.ad_id
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public String getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_alliance.ad_id
     *
     * @param adId the value for ad_alliance.ad_id
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public void setAdId(String adId) {
        this.adId = adId == null ? null : adId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_alliance.park_id
     *
     * @return the value of ad_alliance.park_id
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public String getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_alliance.park_id
     *
     * @param parkId the value for ad_alliance.park_id
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public void setParkId(String parkId) {
        this.parkId = parkId == null ? null : parkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_alliance.partner_id
     *
     * @return the value of ad_alliance.partner_id
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public String getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_alliance.partner_id
     *
     * @param partnerId the value for ad_alliance.partner_id
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId == null ? null : partnerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_alliance.adsense_position_id
     *
     * @return the value of ad_alliance.adsense_position_id
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public Long getAdsensePositionId() {
        return adsensePositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_alliance.adsense_position_id
     *
     * @param adsensePositionId the value for ad_alliance.adsense_position_id
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public void setAdsensePositionId(Long adsensePositionId) {
        this.adsensePositionId = adsensePositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_alliance.uuid
     *
     * @return the value of ad_alliance.uuid
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_alliance.uuid
     *
     * @param uuid the value for ad_alliance.uuid
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_alliance.img_url
     *
     * @return the value of ad_alliance.img_url
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_alliance.img_url
     *
     * @param imgUrl the value for ad_alliance.img_url
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_alliance.redirect_url
     *
     * @return the value of ad_alliance.redirect_url
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public String getRedirectUrl() {
        return redirectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_alliance.redirect_url
     *
     * @param redirectUrl the value for ad_alliance.redirect_url
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public void setRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl == null ? null : redirectUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_alliance.iurl
     *
     * @return the value of ad_alliance.iurl
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public String getIurl() {
        return iurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_alliance.iurl
     *
     * @param iurl the value for ad_alliance.iurl
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public void setIurl(String iurl) {
        this.iurl = iurl == null ? null : iurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_alliance.curl
     *
     * @return the value of ad_alliance.curl
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public String getCurl() {
        return curl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_alliance.curl
     *
     * @param curl the value for ad_alliance.curl
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public void setCurl(String curl) {
        this.curl = curl == null ? null : curl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_alliance.click_status
     *
     * @return the value of ad_alliance.click_status
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public Byte getClickStatus() {
        return clickStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_alliance.click_status
     *
     * @param clickStatus the value for ad_alliance.click_status
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public void setClickStatus(Byte clickStatus) {
        this.clickStatus = clickStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_alliance.create_time
     *
     * @return the value of ad_alliance.create_time
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_alliance.create_time
     *
     * @param createTime the value for ad_alliance.create_time
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_alliance.update_time
     *
     * @return the value of ad_alliance.update_time
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_alliance.update_time
     *
     * @param updateTime the value for ad_alliance.update_time
     *
     * @mbggenerated Wed Dec 30 17:55:53 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}