package com.models;

import java.util.Date;

public class AdInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.name
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.advertiser_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long advertiserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.industry_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long industryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.industry_name
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private String industryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.uuid
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.range_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Byte rangeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.media_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Byte mediaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.asset_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long assetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.url
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.is_redirect
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Byte isRedirect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.status
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.weight
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Short weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.is_substitution
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Byte isSubstitution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.price_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Byte priceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.price
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.price_total
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long priceTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.start_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.ori_start_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Date oriStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.end_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.schedule_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Byte scheduleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.schedule_interval_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Byte scheduleIntervalType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.schedule_interval_hours
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long scheduleIntervalHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.schedule_interval_cnt
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long scheduleIntervalCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.seconds_per
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long secondsPer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.ceiling_cnt_daily
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long ceilingCntDaily;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.app_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.is_api
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Byte isApi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.comment
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.creator_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.operator_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.create_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.update_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.id
     *
     * @return the value of ad_info.id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.id
     *
     * @param id the value for ad_info.id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.name
     *
     * @return the value of ad_info.name
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.name
     *
     * @param name the value for ad_info.name
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.advertiser_id
     *
     * @return the value of ad_info.advertiser_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getAdvertiserId() {
        return advertiserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.advertiser_id
     *
     * @param advertiserId the value for ad_info.advertiser_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setAdvertiserId(Long advertiserId) {
        this.advertiserId = advertiserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.industry_id
     *
     * @return the value of ad_info.industry_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getIndustryId() {
        return industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.industry_id
     *
     * @param industryId the value for ad_info.industry_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setIndustryId(Long industryId) {
        this.industryId = industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.industry_name
     *
     * @return the value of ad_info.industry_name
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public String getIndustryName() {
        return industryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.industry_name
     *
     * @param industryName the value for ad_info.industry_name
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setIndustryName(String industryName) {
        this.industryName = industryName == null ? null : industryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.uuid
     *
     * @return the value of ad_info.uuid
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.uuid
     *
     * @param uuid the value for ad_info.uuid
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.range_type
     *
     * @return the value of ad_info.range_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Byte getRangeType() {
        return rangeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.range_type
     *
     * @param rangeType the value for ad_info.range_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setRangeType(Byte rangeType) {
        this.rangeType = rangeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.type
     *
     * @return the value of ad_info.type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.type
     *
     * @param type the value for ad_info.type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.media_type
     *
     * @return the value of ad_info.media_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Byte getMediaType() {
        return mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.media_type
     *
     * @param mediaType the value for ad_info.media_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setMediaType(Byte mediaType) {
        this.mediaType = mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.asset_id
     *
     * @return the value of ad_info.asset_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getAssetId() {
        return assetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.asset_id
     *
     * @param assetId the value for ad_info.asset_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setAssetId(Long assetId) {
        this.assetId = assetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.url
     *
     * @return the value of ad_info.url
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.url
     *
     * @param url the value for ad_info.url
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.is_redirect
     *
     * @return the value of ad_info.is_redirect
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Byte getIsRedirect() {
        return isRedirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.is_redirect
     *
     * @param isRedirect the value for ad_info.is_redirect
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setIsRedirect(Byte isRedirect) {
        this.isRedirect = isRedirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.status
     *
     * @return the value of ad_info.status
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.status
     *
     * @param status the value for ad_info.status
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.weight
     *
     * @return the value of ad_info.weight
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Short getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.weight
     *
     * @param weight the value for ad_info.weight
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setWeight(Short weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.is_substitution
     *
     * @return the value of ad_info.is_substitution
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Byte getIsSubstitution() {
        return isSubstitution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.is_substitution
     *
     * @param isSubstitution the value for ad_info.is_substitution
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setIsSubstitution(Byte isSubstitution) {
        this.isSubstitution = isSubstitution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.price_type
     *
     * @return the value of ad_info.price_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Byte getPriceType() {
        return priceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.price_type
     *
     * @param priceType the value for ad_info.price_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setPriceType(Byte priceType) {
        this.priceType = priceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.price
     *
     * @return the value of ad_info.price
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.price
     *
     * @param price the value for ad_info.price
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.price_total
     *
     * @return the value of ad_info.price_total
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getPriceTotal() {
        return priceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.price_total
     *
     * @param priceTotal the value for ad_info.price_total
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setPriceTotal(Long priceTotal) {
        this.priceTotal = priceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.start_time
     *
     * @return the value of ad_info.start_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.start_time
     *
     * @param startTime the value for ad_info.start_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.ori_start_time
     *
     * @return the value of ad_info.ori_start_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Date getOriStartTime() {
        return oriStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.ori_start_time
     *
     * @param oriStartTime the value for ad_info.ori_start_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setOriStartTime(Date oriStartTime) {
        this.oriStartTime = oriStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.end_time
     *
     * @return the value of ad_info.end_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.end_time
     *
     * @param endTime the value for ad_info.end_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.schedule_type
     *
     * @return the value of ad_info.schedule_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Byte getScheduleType() {
        return scheduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.schedule_type
     *
     * @param scheduleType the value for ad_info.schedule_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setScheduleType(Byte scheduleType) {
        this.scheduleType = scheduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.schedule_interval_type
     *
     * @return the value of ad_info.schedule_interval_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Byte getScheduleIntervalType() {
        return scheduleIntervalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.schedule_interval_type
     *
     * @param scheduleIntervalType the value for ad_info.schedule_interval_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setScheduleIntervalType(Byte scheduleIntervalType) {
        this.scheduleIntervalType = scheduleIntervalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.schedule_interval_hours
     *
     * @return the value of ad_info.schedule_interval_hours
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getScheduleIntervalHours() {
        return scheduleIntervalHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.schedule_interval_hours
     *
     * @param scheduleIntervalHours the value for ad_info.schedule_interval_hours
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setScheduleIntervalHours(Long scheduleIntervalHours) {
        this.scheduleIntervalHours = scheduleIntervalHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.schedule_interval_cnt
     *
     * @return the value of ad_info.schedule_interval_cnt
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getScheduleIntervalCnt() {
        return scheduleIntervalCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.schedule_interval_cnt
     *
     * @param scheduleIntervalCnt the value for ad_info.schedule_interval_cnt
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setScheduleIntervalCnt(Long scheduleIntervalCnt) {
        this.scheduleIntervalCnt = scheduleIntervalCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.seconds_per
     *
     * @return the value of ad_info.seconds_per
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getSecondsPer() {
        return secondsPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.seconds_per
     *
     * @param secondsPer the value for ad_info.seconds_per
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setSecondsPer(Long secondsPer) {
        this.secondsPer = secondsPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.ceiling_cnt_daily
     *
     * @return the value of ad_info.ceiling_cnt_daily
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getCeilingCntDaily() {
        return ceilingCntDaily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.ceiling_cnt_daily
     *
     * @param ceilingCntDaily the value for ad_info.ceiling_cnt_daily
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setCeilingCntDaily(Long ceilingCntDaily) {
        this.ceilingCntDaily = ceilingCntDaily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.app_id
     *
     * @return the value of ad_info.app_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.app_id
     *
     * @param appId the value for ad_info.app_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.is_api
     *
     * @return the value of ad_info.is_api
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Byte getIsApi() {
        return isApi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.is_api
     *
     * @param isApi the value for ad_info.is_api
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setIsApi(Byte isApi) {
        this.isApi = isApi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.comment
     *
     * @return the value of ad_info.comment
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.comment
     *
     * @param comment the value for ad_info.comment
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.creator_id
     *
     * @return the value of ad_info.creator_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.creator_id
     *
     * @param creatorId the value for ad_info.creator_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.operator_id
     *
     * @return the value of ad_info.operator_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.operator_id
     *
     * @param operatorId the value for ad_info.operator_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.create_time
     *
     * @return the value of ad_info.create_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.create_time
     *
     * @param createTime the value for ad_info.create_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.update_time
     *
     * @return the value of ad_info.update_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.update_time
     *
     * @param updateTime the value for ad_info.update_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}