package com.models;

import java.util.Date;

public class positionInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adsense_position_info.id
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adsense_position_info.position_name
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    private String positionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adsense_position_info.ad_type
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    private Byte adType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adsense_position_info.price_min
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    private Long priceMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adsense_position_info.price_max
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    private Long priceMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adsense_position_info.create_time
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adsense_position_info.update_time
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adsense_position_info.id
     *
     * @return the value of adsense_position_info.id
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adsense_position_info.id
     *
     * @param id the value for adsense_position_info.id
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adsense_position_info.position_name
     *
     * @return the value of adsense_position_info.position_name
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adsense_position_info.position_name
     *
     * @param positionName the value for adsense_position_info.position_name
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adsense_position_info.ad_type
     *
     * @return the value of adsense_position_info.ad_type
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    public Byte getAdType() {
        return adType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adsense_position_info.ad_type
     *
     * @param adType the value for adsense_position_info.ad_type
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    public void setAdType(Byte adType) {
        this.adType = adType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adsense_position_info.price_min
     *
     * @return the value of adsense_position_info.price_min
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    public Long getPriceMin() {
        return priceMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adsense_position_info.price_min
     *
     * @param priceMin the value for adsense_position_info.price_min
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    public void setPriceMin(Long priceMin) {
        this.priceMin = priceMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adsense_position_info.price_max
     *
     * @return the value of adsense_position_info.price_max
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    public Long getPriceMax() {
        return priceMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adsense_position_info.price_max
     *
     * @param priceMax the value for adsense_position_info.price_max
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    public void setPriceMax(Long priceMax) {
        this.priceMax = priceMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adsense_position_info.create_time
     *
     * @return the value of adsense_position_info.create_time
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adsense_position_info.create_time
     *
     * @param createTime the value for adsense_position_info.create_time
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adsense_position_info.update_time
     *
     * @return the value of adsense_position_info.update_time
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adsense_position_info.update_time
     *
     * @param updateTime the value for adsense_position_info.update_time
     *
     * @mbggenerated Wed Dec 09 14:05:25 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}