package com.models;

import java.util.Date;

public class TrafficInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.traffic_name
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private String trafficName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.entity_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Byte entityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.client_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private String clientType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.city_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.parking_cnt
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long parkingCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.parking_on_cnt
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long parkingOnCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.contact_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long contactId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.manager_name
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private String managerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.operator_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.partner_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private String partnerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.user_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.public_key
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private String publicKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.private_key
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private String privateKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.source
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.comment
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.status
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.whitelisted
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Byte whitelisted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.profit_share
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long profitShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.user_status
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Byte userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.create_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.update_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.account_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private Long accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_info.json_str
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    private String jsonStr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.id
     *
     * @return the value of traffic_info.id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.id
     *
     * @param id the value for traffic_info.id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.traffic_name
     *
     * @return the value of traffic_info.traffic_name
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public String getTrafficName() {
        return trafficName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.traffic_name
     *
     * @param trafficName the value for traffic_info.traffic_name
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setTrafficName(String trafficName) {
        this.trafficName = trafficName == null ? null : trafficName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.entity_type
     *
     * @return the value of traffic_info.entity_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Byte getEntityType() {
        return entityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.entity_type
     *
     * @param entityType the value for traffic_info.entity_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setEntityType(Byte entityType) {
        this.entityType = entityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.type
     *
     * @return the value of traffic_info.type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.type
     *
     * @param type the value for traffic_info.type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.client_type
     *
     * @return the value of traffic_info.client_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.client_type
     *
     * @param clientType the value for traffic_info.client_type
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setClientType(String clientType) {
        this.clientType = clientType == null ? null : clientType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.city_id
     *
     * @return the value of traffic_info.city_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.city_id
     *
     * @param cityId the value for traffic_info.city_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.parking_cnt
     *
     * @return the value of traffic_info.parking_cnt
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getParkingCnt() {
        return parkingCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.parking_cnt
     *
     * @param parkingCnt the value for traffic_info.parking_cnt
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setParkingCnt(Long parkingCnt) {
        this.parkingCnt = parkingCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.parking_on_cnt
     *
     * @return the value of traffic_info.parking_on_cnt
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getParkingOnCnt() {
        return parkingOnCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.parking_on_cnt
     *
     * @param parkingOnCnt the value for traffic_info.parking_on_cnt
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setParkingOnCnt(Long parkingOnCnt) {
        this.parkingOnCnt = parkingOnCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.contact_id
     *
     * @return the value of traffic_info.contact_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getContactId() {
        return contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.contact_id
     *
     * @param contactId the value for traffic_info.contact_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setContactId(Long contactId) {
        this.contactId = contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.manager_name
     *
     * @return the value of traffic_info.manager_name
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.manager_name
     *
     * @param managerName the value for traffic_info.manager_name
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.operator_id
     *
     * @return the value of traffic_info.operator_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.operator_id
     *
     * @param operatorId the value for traffic_info.operator_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.partner_id
     *
     * @return the value of traffic_info.partner_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public String getPartnerId() {

        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.partner_id
     *
     * @param partnerId the value for traffic_info.partner_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId == null ? null : partnerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.user_id
     *
     * @return the value of traffic_info.user_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.user_id
     *
     * @param userId the value for traffic_info.user_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.public_key
     *
     * @return the value of traffic_info.public_key
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public String getPublicKey() {
        return publicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.public_key
     *
     * @param publicKey the value for traffic_info.public_key
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey == null ? null : publicKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.private_key
     *
     * @return the value of traffic_info.private_key
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public String getPrivateKey() {
        return privateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.private_key
     *
     * @param privateKey the value for traffic_info.private_key
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setPrivateKey(String privateKey) {
        this.privateKey = privateKey == null ? null : privateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.source
     *
     * @return the value of traffic_info.source
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.source
     *
     * @param source the value for traffic_info.source
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.comment
     *
     * @return the value of traffic_info.comment
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.comment
     *
     * @param comment the value for traffic_info.comment
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.status
     *
     * @return the value of traffic_info.status
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.status
     *
     * @param status the value for traffic_info.status
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.whitelisted
     *
     * @return the value of traffic_info.whitelisted
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Byte getWhitelisted() {
        return whitelisted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.whitelisted
     *
     * @param whitelisted the value for traffic_info.whitelisted
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setWhitelisted(Byte whitelisted) {
        this.whitelisted = whitelisted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.profit_share
     *
     * @return the value of traffic_info.profit_share
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getProfitShare() {
        return profitShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.profit_share
     *
     * @param profitShare the value for traffic_info.profit_share
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setProfitShare(Long profitShare) {
        this.profitShare = profitShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.user_status
     *
     * @return the value of traffic_info.user_status
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Byte getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.user_status
     *
     * @param userStatus the value for traffic_info.user_status
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setUserStatus(Byte userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.create_time
     *
     * @return the value of traffic_info.create_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.create_time
     *
     * @param createTime the value for traffic_info.create_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.update_time
     *
     * @return the value of traffic_info.update_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.update_time
     *
     * @param updateTime the value for traffic_info.update_time
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.account_id
     *
     * @return the value of traffic_info.account_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.account_id
     *
     * @param accountId the value for traffic_info.account_id
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_info.json_str
     *
     * @return the value of traffic_info.json_str
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public String getJsonStr() {
        return jsonStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_info.json_str
     *
     * @param jsonStr the value for traffic_info.json_str
     *
     * @mbggenerated Tue Dec 08 15:11:27 CST 2020
     */
    public void setJsonStr(String jsonStr) {
        this.jsonStr = jsonStr == null ? null : jsonStr.trim();
    }
}